Front_foto_index:
    path:     /
    defaults: { _controller: "FrontTopBundle:Foto:index" }
    methods:  GET

Front_foto_show:
    path:     /{id}/show
    defaults: { _controller: "FrontTopBundle:Foto:show" }
    methods:  GET

Front_foto_new:
    path:     /new
    defaults: { _controller: "FrontTopBundle:Foto:new" }
    methods:  [GET, POST]

Front_foto_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontTopBundle:Foto:edit" }
    methods:  [GET, POST]

Front_foto_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontTopBundle:Foto:delete" }
    methods:  DELETE
